const content=document.querySelector('#content'),search=document.querySelector('#search'),filter=document.querySelector('#filter'),updated=document.querySelector('#updated'),errorBox=document.querySelector('#error');let view='nodes',data=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badge=v=>`<span class="badge ${esc(v)}">${esc(v)}</span>`;
async function api(path){const r=await fetch(path,{credentials:'same-origin'});if(r.status===401){location='/login';throw new Error('Authentication required')}if(!r.ok)throw new Error((await r.json()).error||`HTTP ${r.status}`);return r.json()}
function setFilters(){const vals=view==='nodes'?['ready','draining','down','stale','unknown']:['pending','running','stopped','failed','unknown'];filter.innerHTML='<option value="">All states</option>'+vals.map(v=>`<option>${v}</option>`).join('')}
function render(){const q=search.value.toLowerCase(),f=filter.value;const items=data.filter(x=>(x.node_id||x.name).toLowerCase().includes(q)&&(!f||x.state===f));if(view==='nodes'){content.innerHTML=`<table><thead><tr><th>Node</th><th>State</th><th>Last seen</th><th>Services</th><th>vCPU</th><th>Memory</th></tr></thead><tbody>${items.map(n=>`<tr><td><a href="#node/${encodeURIComponent(n.node_id)}">${esc(n.node_id)}</a></td><td>${badge(n.state)}</td><td>${n.status_age_seconds??0}s ago</td><td>${n.running_services}/${n.desired_services}</td><td>${n.allocated.vcpus}/${n.capacity.vcpus}</td><td>${n.allocated.memory_mb}/${n.capacity.memory_mb} MB</td></tr>`).join('')}</tbody></table>`}else{content.innerHTML=`<table><thead><tr><th>Service</th><th>Node</th><th>State</th><th>Health</th><th>vCPU</th><th>Memory</th></tr></thead><tbody>${items.map(s=>`<tr><td><a href="#service/${encodeURIComponent(s.name)}">${esc(s.name)}</a></td><td>${s.node?`<a href="#node/${encodeURIComponent(s.node)}">${esc(s.node)}</a>`:'-'}</td><td>${badge(s.state)}</td><td>${badge(s.health)}</td><td>${s.vcpus}</td><td>${s.memory_mb} MB</td></tr>`).join('')}</tbody></table>`}}
async function load(){errorBox.hidden=true;try{const hash=location.hash.slice(1);if(hash.startsWith('node/'))return detail('nodes',hash.slice(5));if(hash.startsWith('service/'))return detail('services',hash.slice(8));const out=await api(`/v1/${view}`);data=out.items;updated.textContent=`Updated ${new Date(out.observed_at).toLocaleTimeString()}`;render()}catch(e){errorBox.textContent=e.message;errorBox.hidden=false}}
async function detail(kind,id){const d=await api(`/v1/${kind}/${encodeURIComponent(decodeURIComponent(id))}`);updated.textContent=`Updated ${new Date(d.observed_at).toLocaleTimeString()}`;const pairs=Object.entries(d).filter(([k,v])=>!['api_version','observed_at','services','conditions','port_forwards','health_check'].includes(k)&&typeof v!=='object');content.innerHTML=`<p><a href="#">← Back</a></p><div class="detail"><h2>${esc(d.node_id||d.name)}</h2><dl>${pairs.map(([k,v])=>`<dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${d.services?`<h3>Services</h3><ul>${d.services.map(s=>`<li><a href="#service/${encodeURIComponent(s.name)}">${esc(s.name)}</a> ${badge(s.state)} ${badge(s.health)}</li>`).join('')}</ul>`:''}</div>`}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;location.hash='';setFilters();load()});search.oninput=render;filter.onchange=render;window.onhashchange=load;setFilters();load();setInterval(load,7500);
