# Enriched node config — this is what the agent reads.
#
# In the S3 flow: the enricher Lambda generates this file from the
# minimal service specs in enricher-input/ and writes it to S3.
#
# In the Git flow: you write this file by hand and commit it to the
# config repo at nodes/<node-name>.yaml.
node: "node-1"

services:
  - name: "web-api"
    image: "/var/lib/images/web-api-rootfs.ext4"
    kernel: "/var/lib/images/vmlinux-5.10"
    vcpus: 2
    memory_mb: 512
    kernel_args: "console=ttyS0 reboot=k panic=1 pci=off init=/sbin/fc-init ip=172.16.0.2::172.16.0.1:255.255.255.0::eth0:off"
    network:
      interface: "tap-web-api"
      guest_mac: "AA:FC:00:00:00:01"
      guest_ip: "172.16.0.2"
    port_forwards:
      - host_port: 80
        vm_port: 8080
    health_check:
      type: "http"
      port: 8080
      path: "/health"
      interval: "10s"
      timeout: "5s"
      retries: 3
    metadata:
      environment: "production"
      version: "1.2.3"

  - name: "worker"
    image: "/var/lib/images/worker-rootfs.ext4"
    kernel: "/var/lib/images/vmlinux-5.10"
    vcpus: 4
    memory_mb: 1024
    kernel_args: "console=ttyS0 reboot=k panic=1 pci=off init=/sbin/fc-init ip=172.16.0.3::172.16.0.1:255.255.255.0::eth0:off"
    network:
      interface: "tap-worker"
      guest_mac: "AA:FC:00:00:00:02"
      guest_ip: "172.16.0.3"
    health_check:
      type: "tcp"
      port: 9090
      interval: "15s"
      timeout: "5s"
      retries: 5
    metadata:
      environment: "production"
      version: "2.0.0"
